version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 16-bullseye

    volumes:
      - ..:/workspace:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    network_mode: service:db

  db:
    image: arm64v8/mysql:oracle
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password

  storage:
    image: quay.io/minio/minio
    command: server /minio/data --console-address ":9001" 
    environment:
     MINIO_ROOT_USER: AKIAIOSFODNN7EXAMPLE
     MINIO_ROOT_PASSWORD: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    network_mode: service:db